name = "LinearDecisionRules"
uuid = "ee4db4e3-7eec-47e5-9935-9699b02754f6"
authors = ["Bernado Freitas Paulo da Costa, Joaquim Dias Garcia"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"
Distributions = "0.25"
JuMP = "1.20"
MathOptInterface = "1.27"
